modLoader = "javafml" #mandatory
loaderVersion = "[36,)"
license = "All rights reserved"
issueTrackerURL = "${mod_issues_link}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_display_name}"
displayURL="${mod_website_link}"
logoFile = "icon.png"
credits = ""
authors = "mcrobertx22"
description = '''
Obelisks of the Ancients spawn across the world, can you conquer them?
'''
[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "library_of_exile"
mandatory = true
versionRange = "[1.5.5,)"
ordering = "NONE"
side = "BOTH"